-   id: go-build
    name: 'go-build'
    entry: run-go-build.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go build`, requires golang"    
-   id: go-doc
    name: go-doc
    entry: run-go-doc.sh
    language: 'script'
    description: "Runs `godoc2md`, requires godoc2md"
-   id: go-fmt
    name: 'go fmt'
    entry: run-go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"
-   id: validate-toml
    name: 'validate toml'
    entry: 'tomlv'
    files: '\.toml$'
    language: 'system'
    description: "Runs `tomlv`, requires https://github.com/BurntSushi/toml/tree/master/cmd/tomlv"
